### ISSUE TITLE
Generate a common `ParsedReactionNetwork` structure with ReactioNNetworkImporters

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/SBMLImporter.jl#16]
Should have though of this earlier, but just realised, sorry.

ReactionNetworkImproters (https://github.com/SciML/ReactionNetworkImporters.jl?tab=readme-ov-file) implements a special `ParsedReactionNetwork` structure, which is the output when a reaction network model is read from a file. It contains the `ReactionSystem` model, but also other stuff like parameter values. This is the current structure (from https://github.com/SciML/ReactionNetworkImporters.jl/blob/master/src/ReactionNetworkImporters.jl):
```julia
struct ParsedReactionNetwork
    "Catalyst Network"
    rn::ReactionSystem

    "Dict mapping initial condition symbolic variables to values."
    u0::Any

    "Dict mapping parameter symbolic variables to values."
    p::Any

    "Dict mapping symbolic variable for species names to full string for species name"
    varstonames::Any

    "Dict from group name (as string) to corresponding symbolic variable"
    groupstosyms::Any
end
``` 

Would it make sense to try an make SBMLImporter generate a struct of the same type? Currently, events are created separately as callbacks, so a field would need to be added for these as well. But if possible, one could do things like creating overloads `ODEProblem(prn::ParsedReactionNetwork)`, which both ReactionNetworkImporters and SBMLImporter could use.

**Comment by sebapersson** [comment]
This sounds a good idea and would definitely make sense, and should be something to have before reaching v1.0. Some questions before doing this though:

1. Adding a field for callback makes sense, but for overloads like `ODEProblem(prn::ParsedReactionNetwork)` do you know if there is anywhere callbacks can be stored in a `System` and a `Problem` struct? (feels like it should be feasible as ModelingToolkit supports callbacks?)

Moreover, before this some things should be addressed in the importer:
1. We also currently return `compute_tstops`. It should no longer be needed with https://github.com/SciML/DiffEqCallbacks.jl/issues/178, so fixing this issue should probably be done first. 
2. There is also that for model with `ifelse` we output a function vector `ifelse_t0`, this one can be removed I think by calling an initialization function for the corresponding `ifelse` callback  #17 

So can add this when both these issues are fixed (so that the struct does not get unnecessarily complex).

**Comment by TorkelE** [comment]
Yes, regarding dispatches, there is no good way of dealing with callbacks. We could throw a warning for models with this to ensure the iser is aware, but that is probably the best (or refuse to create the `ODEProblem` overload entirely). Long term, if MTK events can become compatible with SBML ones, then we could simply stick the events in the generated `ReactionSystem` and everything is good.

Yeah, let's have a look at this when everything else is ready though.
